version: '2'
services:
  maintenanceinfoapplication-app:
    image: maintenanceinfoapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://maintenanceinfoapplication-mysql:3306/maintenanceinfoapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://maintenanceinfoapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://maintenanceinfoapplication-elasticsearch:9200
    ports:
      - 8081:8081
  maintenanceinfoapplication-mysql:
    extends:
      file: mysql.yml
      service: maintenanceinfoapplication-mysql
  maintenanceinfoapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: maintenanceinfoapplication-elasticsearch
